### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by yflscorpio** [apokryphus/advanced-combat-system#10]
3.9.6 version of the sword claw and scythe roll will make the game crash, sometimes there will be a card trigger problem, can not add a condition on the trigger, ordinary light attack to reset the trigger action determination?

**Comment by apokryphus** [comment]
Currently on break. Will push fix either today or tomorrow

**Comment by apokryphus** [comment]
Nothing to be sorry for! 

Fixed now. Probably.
