### ISSUE TITLE
Thanks for fixing

### ISSUE THREAD

**Issue by yflscorpio** [apokryphus/advanced-combat-system#11]
I tested your fixed mod first, it's great! It's just that I mentioned the problem of stuck action triggers, for example, when I'm using another weapon form, double-clicking on W, dodge attack will be stuck trigger, then I can't use another weapon form and skill, only until the battle is over or switch to another sword can it trigger again, so I was wondering if it's possible to add a judgment that when you use the original normal weapon form to lightly attack, you can reset all trigger conditions and go back to       to the original trigger point? That way, even if there's a stuck form, we can return to the trigger condition again with a normal light attack.

**Comment by apokryphus** [comment]
I'm not sure I understand the problem here. Double-tapping W either performs the bruxa bite special attack if the player has full adrenaline and the option is enabled in the menu, which can be canceled by pressing dodge or roll, or it performs a dash attack. 

I'm not getting any "stuck trigger" problems at all.

**Comment by yflscorpio** [comment]
Thank you for your reply, it may be that I installed some other mod, it will appear in your mod, weapon morphing form sometimes stuck, that is, only maintain the weapon form, but can not trigger the skills, if the hybrid mode, also can not switch weapons, only manually change weapons or the end of the battle, re-enter the battle, to trigger the form and skills again. So after several tests, I think it may be a trigger judgment condition problem.

**Comment by yflscorpio** [comment]
If you have time, you can install the following mod to test it out.
https://www.nexusmods.com/witcher3/mods/5007
Select a belt
Tome of Transference.
 Use
Igni to attack, you will see the problem I mentioned.
  Thank you very much for your patience, listening and replying to my questions.

**Comment by yflscorpio** [comment]
Your MOD and his MOD, a change of weapon action set, a change of spell action set, which makes the monotonous Witcher 3 game becomes very interesting, you can choose their favorite weapons and spells to face, adventure, explore the world, really great, this is the real wolf school of demon hunter look!
You can also try it when you have time, I believe you will also like it!

**Comment by apokryphus** [comment]
No problem at all. Unfortunately, I'm not very interested in spending too much time making ACS compatible with everything. If Magic Spells happens to interfere with it, I'm most likely not going to do anything about it.

**Comment by yflscorpio** [comment]
Oh, I see, but thank you for your patience in replying, I now if the problem I mentioned occurs, I found that I can manually switch weapons in battle and then hit the target.
Because the game itself has a judgment, when you use the steel sword on the monster can not have damage, then the game will automatically help you switch back to the silver sword can damage the monster, so it is just one more operation steps
