### ISSUE TITLE
Ciri's Silver sword

### ISSUE THREAD

**Issue by yflscorpio** [apokryphus/advanced-combat-system#12]
Hi, regarding Ciri Silver sword weapon, is it possible to change to 'Torzirael', as your current Ciri weapon is 'q505 crafted sword', which has no damage and does no damage to monsters?

**Comment by apokryphus** [comment]
Well I don't know what other mods you have installed, but it does damage to monsters just fine for me, so I'm not changing it. Ciri's powers are only available for weapons that belong to her, and while Tor Zireael has Zireael in its name, its ultimately not her sword.

Normal steel Zireael will also deal damage to monsters though. ACS allows steel weapons to damage monsters and silver weapons to damage humans.

**Comment by yflscorpio** [comment]
The steel sword is possible to cause damage to human enemies, but the silver sword has no damage to monsters, so according to you to turn on the damage to monsters in your mod is it?

**Comment by yflscorpio** [comment]
Because I did not use the manual scabbard, the game will automatically change the sword according to the enemy, or do I have to use the manual scabbard, using the steel sword to cause damage to the monster class enemy?

**Comment by apokryphus** [comment]
You could do that, yes. Just enable `Manual sword drawing / sheathing` in the `Options/Gameplay` menu.

**Comment by yflscorpio** [comment]
Thank you, I seem to understand your original intention, in fact, as long as you wear a sword on it, do not wear two, I always wear two swords, so I found 2 Ciri weapons, there is a silver sword is no damage

**Comment by yflscorpio** [comment]
It turns out that you can set the damage in your MOD damage, the sword will have damage, that option I have always been closed
