### ISSUE TITLE
Version 4.0.6 test report

### ISSUE THREAD

**Issue by yflscorpio** [apokryphus/advanced-combat-system#16]
After installation found a very serious FPS reduction problem, at first thought it was an official driver problem, return to the previous version or the same FPS reduction, reinstall your 4.0.5 version of the problem no longer appear

**Comment by apokryphus** [comment]
Hmm I probably know why. Install 4.0.6 again and drag this into your mods folder and replace file. Check and see if there is still an FPS problem.
[mod_ACS.zip](https://github.com/apokryphus/advanced-combat-system/files/11644284/mod_ACS.zip)

**Comment by yflscorpio** [comment]
Ok fixed
