### ISSUE TITLE
Version 4.0.7 test report

### ISSUE THREAD

**Issue by yflscorpio** [apokryphus/advanced-combat-system#17]
4.0.7 version of the content of personal testing there is no problem, but it seems that the mask show/hide function is disabled?
I wonder what the reason is?
4.0.5 available to 4.0.65 failed

**Comment by apokryphus** [comment]
You mean the button toggle? Works correctly for me. Check if the input is still there in input.settings

**Comment by yflscorpio** [comment]
Checked, input.settings.in file has settings

**Comment by yflscorpio** [comment]
Maybe my other mods are a little conflicting, sometimes available and sometimes not, but thank you very much, thank you!
