### ISSUE TITLE
4.0.8

### ISSUE THREAD

**Issue by yflscorpio** [apokryphus/advanced-combat-system#18]
Hello, I would like to ask if there is a game code for the four pieces of equipment? Two of them are not found

**Comment by apokryphus** [comment]
The armor pieces are dropped after defeating Volos, Loviatar, the Knightmare Eternum, and Khagmar's monster form. The [enemies](https://github.com/apokryphus/advanced-combat-system#8-enemies-1) section will tell you how to find them.

**Comment by apokryphus** [comment]
The Glossary ---> Bestiary section in the ACS mod menu now includes a list of enemies.
