### ISSUE TITLE
Incompatibility

### ISSUE THREAD

**Issue by Madfox11** [apokryphus/advanced-combat-system#3]
Will compatibility with the mod be made ?https://www.nexusmods.com/witcher3/mods/3024

**Comment by apokryphus** [comment]
There is no such thing as compatibility between these mods. Using that mod will apply those animations only when Geralt is holding his default weapons. 

Fortunately, I know how that mod works, and am able to apply that animation to ACS.

**Comment by Madfox11** [comment]
Thank you!!))

**Comment by Madfox11** [comment]
> 

That is, can you make it work?))

**Comment by Madfox11** [comment]
I checked it. In the latest update, the animation of walking is different from the one in fashion, the sword looks forward strongly, the animation of walking in shallow water is used in fashion.((

**Comment by Madfox11** [comment]
In early versions, these mods worked together.
