### ISSUE TITLE
Incompatibility

### ISSUE THREAD

**Issue by Madfox11** [apokryphus/advanced-combat-system#4]
The last addition, which adds walking with a VGX sword, has a different animation, in the original fashion, walking in shallow water is used. Previously, these 2 mods worked together and did not conflict.

**Comment by apokryphus** [comment]
I'm confused. What's the issue here? 

There is no conflict. The other VGX sword walking mod is only applied when Geralt uses his normal sword attacks.

**Comment by Madfox11** [comment]
> Я смущен. В чем проблема?
> 
> Конфликта нет. Другой мод VGX для ходьбы с мечом применяется только тогда, когда Геральт использует свои обычные атаки мечом.

So the animations in VGX fashion and yours are different, the sword looks somewhere ahead.

**Comment by apokryphus** [comment]
Nope. They're the exact same animation. There is only 1 way to do it, and it's this way.

**Comment by Madfox11** [comment]
> Nope. They're the exact same animation. There is only 1 way to do it, and it's this way.

Check and compare, the animations are completely different, holds the weapon with a forward bias, and in the original exactly and further. I have both of them, it's very easy to compare, they are very different.

**Comment by apokryphus** [comment]
Huh. You're right! My apologies, I was wrong. 

Download v1.9, or download it again if you already did that, or run the updater/installer script. I fixed it.

**Comment by apokryphus** [comment]
Keep in mind that if you're using the original VGX sword walking mod you will most likely run into the blurry dialogue issue sooner or later.
