### ISSUE TITLE
Again, problems with the movement of VGX weapons.

### ISSUE THREAD

**Issue by Madfox11** [apokryphus/advanced-combat-system#5]
Again, problems with the movement of VGX weapons. Everything works well... But when he enters the battle mode, it doesn't work while running and he holds the weapon as usual (Well, I mean that during the fight, the movements when you run don't work.

**Comment by apokryphus** [comment]
Yeah it's because I changed how the player holds the weapon while in combat for all the movesets. It breaks if I enable VGX sword walking while in combat as well. I'll probably look more into solving this issue in the future, but since it's not code it's not easily solvable.

**Comment by Madfox11** [comment]
Thanks a lot for the answer)) I'm probably already boring you)) XD

**Comment by apokryphus** [comment]
Nah don't worry about it. Though the sword walking is pretty low on my to-do list, so it might take a while to fix it properly.

**Comment by Madfox11** [comment]
I put it wrong last time.... The VGX moves don't work only when running in combat.... when you just walk slowly in battle, everything works fine (even with mod modes enabled)... but when you start running in battle, he starts using vanilla running with weapons in his hands... In combat, while running, not while walking.

**Comment by Madfox11** [comment]
Thanks for the answer) Now I understand everything)
