### ISSUE TITLE
Function suggestion)

### ISSUE THREAD

**Issue by Madfox11** [apokryphus/advanced-combat-system#6]
Hello!!)) I am shocked and delighted with the work done on this mod and now I can't imagine my game without it) Thank you so much for doing this, you are very cool))) Is it possible to add a function that would remove all the sparkling effects of attack and magic and elixirs? Well, for example, the absorption of vampire health, so that the caretaker's shovel does not have a visual, green effect of absorbing health. Or when you put a glyph or a special rune on the armor of a rune master, then the green effect in battle is triggered, like a vampire absorption, it's very annoying and such a function would just be very useful and irreplaceable, otherwise Geralt sparkles like a Christmas tree during the battle... It's just that sometimes you can't see at all what happens in battle because of these effects))etc

**Comment by apokryphus** [comment]
[mod_no_green_effect_on_player.zip](https://github.com/apokryphus/advanced-combat-system/files/9846132/mod_no_green_effect_on_player.zip)
Try this.

**Comment by Madfox11** [comment]
Uraaaa))!!!It worked)) You were able to solve it so quickly) You are a real professional) But the red effect and the yellow absorption effect still work... these effects are caused by runes that the runemaster applies to weapons and armor. Yellow and red have similar effects on weapons from runes and green effect from buff on armor.

**Comment by apokryphus** [comment]
Ah I need to take a look at the code again to be sure of the effect names. I think those effects might exist in multiple places within the script, and thus would be kind of troublesome to do. I could also directly remove the effects themselves from the player, but it would cause major compatibility issues with other mods. 

But yeah I'll think about it if I want to continue making mods to remove effects. No guarantees. 

By the way, for suggestions, I would recommend you contact me on discord in my channel:
https://discord.gg/xPBgHs42Cb

**Comment by Madfox11** [comment]
thank you very much))
