### ISSUE TITLE
Compilation error

### ISSUE THREAD

**Issue by gndm28** [apokryphus/advanced-combat-system#7]
A few users, me included, have been encountering the compilation error as follows:

Error [mod_acs]local\misc\acs_spawner.ws(4106): syntax error, unexpected '{', near '{'

**Comment by apokryphus** [comment]
Ahhh I must have messed up removing some stuff. I kinda did it in a hurry. Re-download v3.1 and overwrite scripts to fix it for now. I'm about to board a plane so I'll probably need a day to fix it properly.
